### ISSUE TITLE
Feature Request: IMDB ID's for episodes

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#10]
I noticed today that episode IMDB ID's are not scraped, but the IMDB id for the tv show is scraped.

Is it possible to include IMDB UniqueID for **episodes**.

(did we discuss this previously? could not find mention of it, but have the feeling we did)

**Comment by Razzeee** [comment]
Why do you think that this doesn't work?

I debugged it pretty heavily only to discover that it seems fine in the database, given tvdb has the data.
![image](https://user-images.githubusercontent.com/5943908/73374517-9f2b8080-42ba-11ea-8623-753e4266915e.png)

**Comment by KarellenX** [comment]
Hmmm, it is working today. I scraped the same two shows and this time IMDB ID's were present.  Not sure what happened the other day. But until those errors are fixed, maybe my scraping is unreliable.

I'll close this.

**Comment by KarellenX** [comment]
I still cannot figure out the problem with this. It is hit and miss for me. I keep assuming it is part of the larger crashing issue, but I don't know if that is the case.

I have scraped 5 tv shows in the last week, 4 shows did not provide the IMDB ID's, even though the ID's were available at TVDB.

I scraped a larger show of 90 episodes in 9 seasons today
Seasons 1-5 no IMDB ID scraped
Season 6-8 all IMDB ID scraped
Season 9, some IMDB ID's scraped.

The log does not show what metadata is retrieved. Can you add that?

Not sure what info I can post as there is nothing logged for this issue.

**Comment by KarellenX** [comment]
I assume the issue I am experiencing is related to this... https://github.com/xbmc/xbmc/issues/17444
