### ISSUE TITLE
Scraping Errors

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#12]
Two tv shows that exhibit strange scraping issues

The show **3%** is incorrectly scraped and may be a cause for the **tzinfo** errors and crashing issue
https://www.thetvdb.com/series/3-1

Also I tried to scrape Passage (2019) in English...
https://www.thetvdb.com/series/the-passage
but instead I ended up with Passage des Arts from (2020) in French... 
https://www.thetvdb.com/series/passage-des-arts
and most data was missing most likely due to it being the wrong language.
I raise this as the year and language are being ignored.

Could you test and confirm my results?

**Comment by Razzeee** [comment]
Can you post the folder structure + files? Or create a zip with mock files?

**Comment by KarellenX** [comment]
Here... https://ufile.io/ul59fqws

**Comment by Razzeee** [comment]
So `3%` seems to work fine on our end, but tvdb doesn't seem to handle `%` well on their end, and the returned search result is not good. Can you raise that on their end?

The problem with "passage" is that it should be "The passage". I can probably improve the algorithm some more. But not today :)

**Comment by KarellenX** [comment]
Sure, I will post an issue report at TVDB.

Could you give me a bit more detail on how their API is failing?

**Comment by Razzeee** [comment]
Well it returns unrelated items, as far as I can tell.

**Comment by KarellenX** [comment]
Done... https://forums.thetvdb.com/viewtopic.php?f=122&t=62442

**Comment by KarellenX** [comment]
TVDB have confirmed this a problem at their end.

Issue closed

**Comment by KarellenX** [comment]
TVDB have fixed this issue, but there is still another issue affecting the scraping of this show.

https://forums.thetvdb.com/viewtopic.php?p=171661#p171661
