### ISSUE TITLE
<episodeguide> backwards compatibility 

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#13]
Is it possible to enable backwards compatibility with v1 and v2 of the TVDB API.

The v1 `<episodeguide>` looks like this...
```xml
http://www.thetvdb.com/api/1D62F2F90030C444/series/79349/all/en.zip
```

The v2 `<episodeguide>` looks like this...
```xml
https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:79349}|Content-Type=application/json
```

The TVDB ID is **79349** in both examples. 

Is it possible to parse this ID and use it? As stated in another issue report, since the update from v1 to v2 API in Nov 2017, to this day the `<episodeguide>` remains the number one reason on the forum for failed scrapes.

**Comment by jkirsch2** [comment]
Small question...
With the new Python scrapers, is it really necessary to continue to use the <episodeguide> field ?
Can't we simply use the id fields that are already available ?

**Comment by Razzeee** [comment]
It seems to be a bug, that we end up with this, in that path of the scraper.
