### ISSUE TITLE
Search Results- more details

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#14]
I noticed that the Search Results can be ambiguous and leave a user wondering which is the correct show. For example the tv show in the image below has entries for Let's Dance for (2006), (2014), (2012), but it is impossible to determine which is which.

https://www.thetvdb.com/search?menu%5Btype%5D=TV&query=let%27s%20dance

![lets-dance2](https://user-images.githubusercontent.com/44626605/74688212-ec03d680-522a-11ea-9fb5-0b1c299c67d2.jpg)

**Comment by Razzeee** [comment]
I've added the (american style) date when the first episode aired for now. Should be the most unique approach and is the one I have data for.

Some shows now have a year and this date, but that's due to the metadata.

**Comment by KarellenX** [comment]
Great, thanks. Much better. 

Did that affect the search result in some way as only two results are found when there should be three.

![lets-dance4](https://user-images.githubusercontent.com/44626605/74692402-15c4f980-523b-11ea-9975-61114164f7ef.jpg)

**Comment by Razzeee** [comment]
It shouldn't, that's weird.
