### ISSUE TITLE
TVDB Ratings & Votes

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#16]
TVDB have deprecated user Ratings and Votes. 

While existing shows do still have Ratings and Votes data, this data has become stale as users can no longer add their rating.

New shows have no Ratings and Votes.

I think it would be wise to remove the ability to select TVDB ratings from the scraper settings.

I also think that both Trakt and IMDB ratings should be provided by default, and if not by default, allow selection of both, not one or the other.

**Comment by Razzeee** [comment]
Removed the setting here, not sure if it will change you over to a different one upon update. https://github.com/xbmc/metadata.tvdb.com.python/commit/cb30237c2c0194c33bd032029528d2e76f7db681

**Comment by KarellenX** [comment]
Issue closed as TVDB will be releasing their own scraper.
