### ISSUE TITLE
Verbose debug logging

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#3]
Probably something we need to discuss on slack, but can you add additional debug logging for the scraper?

**Comment by Razzeee** [comment]
Absolutly, do you have any ideas for what exactly?

**Comment by KarellenX** [comment]
I'll keep adding to this post as I inspect the logs more and more.

1. The very first mention of scraping is this line...
' VideoInfoScanner: Fetching url '71035' using The TVDB Python scraper (content: 'tvshows')'
The scraper has already found the show at TVDB, but there is no log of contacting TVDB, what was actually searched and what was returned. All I know is "I am downloading 71035". Information on the API call and what was returned is useful in diagnosing failed or incorrect scrapes.

2. When adding episodes, all I see is this single line then lots of artwork caching lines...
`DEBUG: VideoInfoScanner: Adding new item to tvshows:E:\TV Show- TEST\Angel\Season 00\S01E01.avi`
But no information on what is being added.

**Comment by Razzeee** [comment]
Do you have debug logging in kodi enabled? Doesn't sound like it.

**Comment by KarellenX** [comment]
Hehe, of course I do. See the log I posted on slack

**Comment by Razzeee** [comment]
Look for `metadata.tvdb.com.python:` in that log to see what I log.

**Comment by KarellenX** [comment]
Ok, lost sight of some of the log lines with all the spam lines. Lets leave this until other issues are sorted out and log is cleaner.

I normally jump to the start of a scan by searching "Videoinfoscanner" or "cscraper" which seemed to work for the xml scrapers, but there seem to be processes happening with the python scraper before that. I'll just need to adjust reading python scrapers.

**Comment by Razzeee** [comment]
Closing this for now.
