### ISSUE TITLE
Airs before season/episode is mixed up

### ISSUE THREAD

**Issue by rosexcroix** [xbmc/metadata.tvdb.com.python#41]
https://github.com/xbmc/metadata.tvdb.com.python/blob/996536722bb17087840adaecbb17c016b7f2b426/resources/lib/episodes.py

something that airs before episode 1 of season 5 will be listed as airing before episode 5 of season 1. this diff fixes it.

```diff
--- a/episodes.py	2021-11-28 22:00:31.339047103 +0100
+++ b/episodes.py	2021-11-28 22:01:26.259440095 +0100
@@ -79,10 +79,10 @@
 
     if ep.airsAfterSeason and ep.airsAfterSeason >= 0:
         details['sortseason'] = 10000
-        details['sortepisode'] = ep.airsAfterSeason
+        details['sortepisode'] = ep.airsAfterEpisode
     elif ep.airsBeforeSeason and ep.airsBeforeSeason >= 0:
-        details['sortepisode'] = ep.airsBeforeSeason
-        details['sortseason'] = ep.airsBeforeEpisode
+        details['sortepisode'] = ep.airsBeforeEpisode
+        details['sortseason'] = ep.airsBeforeSeason
 
     if (settings.getSettingBool('absolutenumber') == True):
         details['season'] = 1
```

**Comment by KarellenX** [comment]
@rosexcroix 

Is there a particular show where  you experienced this? Could you provide the link to the show.
Thanks.

**Comment by rosexcroix** [comment]
https://thetvdb.com/series/gamecenter-cx/episodes/2466901

kodi xml export
```xml
<displayseason>1</displayseason>
<displayepisode>10</displayepisode>
```
tvdb api
```json
"airsBeforeSeason": 10,
"airsBeforeEpisode": 1,
```

**Comment by KarellenX** [comment]
@rosexcroix 

Thanks, I can confirm your findings. Season and Episode have been mapped backwards.

Trouble is I don't know whether @razzeee is making any fixes to this scraper.

Are you able to create a pull request with the fix?

**Comment by razzeee** [comment]
@KarellenX can you test https://github.com/xbmc/metadata.tvdb.com.python/pull/42

**Comment by KarellenX** [comment]
Sure, I'll do that a bit later today.

Hopefully @rosexcroix can test also

**Comment by rosexcroix** [comment]
it gives me the right info now.

**Comment by KarellenX** [comment]
Thanks. Any errors when you ran that version of the scraper?
