### ISSUE TITLE
NFO Files not working

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.tvdb.com.python#5]
I tested the following...

Full metadata NFO- Working

Parsing NFO with imdb and tvdb links- Not working

Combination NFO- Part working. The section between `<tvshow></tvshow>` was scanned but the link to obtain the rest of the info was not used

**Comment by Razzeee** [comment]
Needs to be tested. Did some work on it, but I don't have a setup with nfo files.

**Comment by KarellenX** [comment]
Tried scanning my library into Kodi using this scraper. The entire library is nfo files - all scraped by Kodi initially, then nfo files created by Export to Separate files. 

Tried scanning His Dark Materials using your scraper. It scans ok using the xml scrapers, but fails here for some reason. The tvshow and first 3 episodes scan ok, then the remaining episodes fail. It keeps asking for the episodeguide but it shouldn't as it is not needed and it was able to scan the first 3 episodes ok, and had no problems scanning about 40 other shows that have no episodeguide.

First fail on line 2243... https://paste.kodi.tv/lijevivuzu.kodi

**Comment by Razzeee** [comment]
The log message in the offending file seems to be from kodi itself, not the scraper. Can you check the file for weird line ending or similar?

**Comment by KarellenX** [comment]
Parsing and Combination NFO files are working correctly

Full metadata nfo files with and without <episodeguide> are working

Issue closed.
